### ISSUE TITLE
Servers not showing in server browser

### ISSUE THREAD

**Issue by EdGotti** [aid7n/h1-master#1]
Hello, i know you may not be able to help as this is just for issues but i have successfully setup the master mirror on a Linux machine and everything is running properly as well as changed the ip and port on the launcher/server launcher. I am receiving messages from my server, i can see the get requests coming from my client machine and responses being sent to the client but i see no servers showing up on the server list. I have ensured the ip in the ts file has been changed and the game filter is correct. I have ensured the ports and protocols are open for inbound/outbound. I really am just out of ideas at this point so i figured id reach out and ask for any advice you could give. The mirror is fetching raidmax servers successfully as well. Thankyou for any advice you could offer

**Comment by aid7n** [comment]
The way the H2M client parses the server list is very slightly different to how I managed to make it work for H1-Mod

This implementation seems to make this work for H2M clients; you need to replace the function `buildGetServersResData` in `/src/services/response.ts` with the following:
```ts
const buildGetServersResData = (servers: IServerItem[]) => {
  const delimiter = Buffer.from("\\", "binary");
  const commandName = Buffer.from("getserversResponse ");

  let responseData = Buffer.concat([blankHeader, commandName, delimiter]);

  servers.forEach((server) => {
    const ipBuffer = Buffer.from(server.ipParts);
    const portBuffer = Buffer.alloc(2);
    portBuffer.writeUInt16BE(server.port, 0);
    responseData = Buffer.concat([
      responseData,
      ipBuffer,
      portBuffer,
      Buffer.from([0x00]),
      delimiter,
    ]);
  });

  responseData = Buffer.concat([responseData, eot]);
  return responseData;
};
```

That changes the commandName to "getServersResponse" and adds a blank `0x00` to the end of each IP:PORT part.

You also need to change the server cfg in `/src/config/server.ts`:
```ts
export const serverCfg: IServerCfg = {
  game: "H2M", // was H1
  protocol: 2,
  udpPort: 20810,
  listFetchTime: 1000 * 60 * 5,
  raidmaxApiUrl: "http://api.raidmax.org:5000/servers",
  mandatoryServerParts: [], // removed the mandatory part
};
```
